fix: remove hard reloads
heyxyz/hey pull request #4183
Opened 2023-12-11 19:02 UTC by neo773

Removes hard reloads in the codebase

https://github.com/heyxyz/hey/assets/62795688/9ecfc7b8-77e5-49c9-9d17-130fefd2c9f6

## Related issues

Fixes #4182

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking small changes to existing functionality)

/claim #4182

2023-12-11 19:51 UTC, bigint requested changes

2023-12-11 19:51 UTC, bigint commented on apps/web/src/components/Common/Layout.tsx
> +      router.push('/');
We don't want to switch pages

2023-12-11 19:51 UTC, bigint commented on apps/web/src/components/Common/Providers/LensSubscriptionsProvider.tsx
> +        router.push('/');
Same here

2023-12-11 19:51 UTC, bigint commented on apps/web/src/components/Shared/Login/WalletSelector.tsx
> +      router.push('/');
Here too

2023-12-11 19:51 UTC, bigint commented on apps/web/src/components/Shared/Navbar/MenuItems.tsx
> +  if (currentProfile !== null) {
Just 'if current profile' works too

2023-12-11 19:51 UTC, bigint commented on apps/web/src/components/Shared/Navbar/MenuItems.tsx
> +  if (sessionProfileId !== null && isAddress(sessionProfileId)) {
No need for null check

2023-12-11 20:17 UTC, neo773 commented
@bigint 
Pushed a new commit

2023-12-12 06:59 UTC, bigint commented
https://github.com/heyxyz/hey/assets/69431456/53b06b61-5502-4e55-8745-282d7bef5301

@neo773 It seems like some data are not updated, I guess something to do with apollo garbage collection or evict all cache on logout

2023-12-12 07:00 UTC, bigint commented
Try with profile on testnet!

2023-12-12 10:02 UTC, bigint requested changes

2023-12-12 10:02 UTC, bigint commented on apps/web/src/components/Common/Layout.tsx
>      resetPro();
I guess we can move all these inside signout method itself so we can just call signout everywhere!

2023-12-12 10:02 UTC, bigint commented on apps/web/src/components/Shared/Navbar/MenuItems.tsx
> +  console.log(sessionProfileId, 'sessionProfileId');
Remove it

2023-12-12 10:02 UTC, bigint commented on packages/lib/getStampFyiURL.ts
> +    return '';
you can return stamp url with null address aka `export const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000';`

2023-12-12 13:20 UTC, neo773 commented
> Screen.Recording.2023-12-12.at.12.28.58.PM.mov 
> @neo773 It seems like some data are not updated, I guess something to do with apollo garbage collection or evict all cache on logout

Expected behaviour is navigating to home page every site does this,
It's impossible to account for the entire state of the App without it getting messy and would be out of scope of the original issue.

2023-12-12 13:30 UTC, bigint commented
We mentioned it on the issue 🙇🏼 

> Make sure we clear all local cache while logging out!

2023-12-12 13:34 UTC, neo773 commented
@bigint 
Is soft reloading current URL acceptable?
Would reset the state with no edge cases.

2023-12-12 13:38 UTC, bigint commented
WDYM soft reloading?

2023-12-12 13:38 UTC, bigint commented
Will it reload the entire app?

2023-12-12 13:39 UTC, neo773 commented
Router refresh, so navigates to same URL

2023-12-12 13:41 UTC, bigint commented
IMO apollo has lot of utils to clear cache or garbage collect stuffs!

On Tue, Dec 12, 2023, at 7:09 PM, neo773 wrote:
> 
> 
> Router refresh, so navigates to same URL
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/heyxyz/hey/pull/4183#issuecomment-1852053010>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AQRXBIDYBREYEWGXC4NLT7LYJBNBFAVCNFSM6AAAAABAQIDASKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJSGA2TGMBRGA>.
> You are receiving this because you were mentioned.Message ID: ***@***.***>
>

2023-12-12 13:43 UTC, bigint commented
```
const { resetStore } = useApolloClient()
```

2023-12-15 17:03 UTC, bigint commented
is this good to review?

2023-12-15 17:04 UTC, neo773 commented
@bigint 
nah left a message on discord

2023-12-17 08:08 UTC, bigint commented
Closing this, we can rethink this later!

2023-12-17 08:08 UTC, closed without merging