fix: Disable scroll on react calendar on profile stats page
heyxyz/hey pull request #4192
Opened 2023-12-12 10:33 UTC by neo773

Disables scroll on react calendar on profile stats page
This also auto scrolls the calendar on x axis so only recent months are shown as disabling scroll would hide them

https://github.com/heyxyz/hey/assets/62795688/0d2fcd36-77a8-475c-bb87-4b25eece3473

/fixes #4191
/claim #4191

2023-12-12 10:56 UTC, bigint commented
@neo773 I dont see december here

Hey Prod

<img width="492" alt="Screenshot 2023-12-12 at 4 26 39 PM" src="https://github.com/heyxyz/hey/assets/69431456/600c78f9-26ca-4586-95e0-696b812e97d6">

Preview

<img width="563" alt="Screenshot 2023-12-12 at 4 26 52 PM" src="https://github.com/heyxyz/hey/assets/69431456/0d49ef1b-6ede-4d53-91a1-b74d0763717f">

2023-12-12 11:04 UTC, neo773 commented
@bigint 
Like I said we're scrolling to right side of the element, wouldn't make sense to show older months and hide the newer ones would it?

2023-12-12 11:09 UTC, rishi-raj-jain commented
@bigint @neo773 

How about using CSS on the parent div to hide the scrollbar but the functionality of scroll be there?

2023-12-12 11:32 UTC, bigint commented
Ummm not sure, the best would be dynamic sizing of the grid

2023-12-14 00:33 UTC, neo773 commented
@bigint 
Found an easier pure CSS fix, the grid is now sized dynamically

2023-12-14 05:09 UTC, bigint requested changes

2023-12-14 05:09 UTC, bigint commented on apps/web/src/styles.css
seems like prettier not got applied in this file!

2023-12-14 05:09 UTC, bigint commented on apps/web/src/components/Profile/Achievements/Streaks.tsx
> +import { type FC } from 'react';
types should be always declared above!

2023-12-14 05:10 UTC, bigint commented
<img width="536" alt="Screenshot 2023-12-14 at 10 39 55 AM" src="https://github.com/heyxyz/hey/assets/69431456/9df4225e-1e29-497b-936b-f21559231361">

im still seeing this, github handles it nicely!

2023-12-14 05:22 UTC, bigint commented
Fixed in https://github.com/heyxyz/hey/pull/4228

2023-12-14 05:22 UTC, closed without merging