feat: XMTP integration.
heyxyz/hey pull request #4241
Opened 2023-12-16 22:03 UTC by b4s36t4

## What does this PR do?

## Related issues

Fixes #4240
/claim #4240

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Enhancement (non-breaking small changes to existing functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Explanation of the changes

This PR adds the chat capability to the hey platform using XMTP as the core protocol.

- [x] Integrated `@xmtp/react-sdk` package into the core.
- [x] Client initialization i.e create XMTP profile or Sign with wallet
- [x] Support for single time authentication by storeing keys into indexdb(can be discussed whether to include or not) 
- [x] Creating Initial Screen for the chat page
- [x] Added support/button in the user's profile page, will only visible if the other profile also have xmtp account.

## Additional Info.
- References:

- Demo

Work done by: @5war00p @b4s36t4

2023-12-16 22:06 UTC, b4s36t4 commented
@bigint Requesting for review.

2023-12-16 22:13 UTC, 5war00p commented
References for storing keys: 
- https://xmtp.org/docs/faq#why-do-apps-built-with-xmtp-require-a-user-to-sign-with-their-blockchain-account-private-keys-each-time-they-start-a-new-messaging-session
- https://github.com/xmtp/xmtp-web/tree/main/packages/react-sdk
- https://xmtp.org/docs/build/authentication#saving-keys

Demo video: 
https://github.com/heyxyz/hey/assets/57614947/97d6a818-a177-4ea9-b30b-53a9ad586801

2023-12-17 06:43 UTC, bigint requested changes

2023-12-17 06:43 UTC, bigint commented on apps/web/src/components/Chat/ChatsView.tsx
Rename chat to messages everywhere!

2023-12-17 06:43 UTC, bigint commented on apps/web/src/components/Chat/ChatsView.tsx
> +const ChatsView = () => {
ass `:FC`

2023-12-17 06:43 UTC, bigint commented on apps/web/src/components/Chat/ChatsView.tsx
> +  if (isLoaded && conversations.length === 0) {
do we need isLoaded? cuz isLoading is already checked!

2023-12-17 06:43 UTC, bigint commented on apps/web/src/components/Common/Providers/index.tsx
> +      <XMTPProvider contentTypeConfigs={baseContentTypeConfigs} dbVersion={1}>
IMO xmtp provider can be wrapped only on messages page, global provider will increase size or it will consume more memory, might lead to memory leak!

2023-12-17 06:43 UTC, bigint commented on apps/web/src/components/Profile/Details.tsx
> +  useEffect(() => {
try useUpdateEffect hook

2023-12-17 06:43 UTC, bigint commented on apps/web/src/components/Profile/Details.tsx
> +    if (isLoading) {
```suggestion
    }

    if (isLoading) {
```

2023-12-17 06:43 UTC, bigint commented on apps/web/src/components/Shared/Login/WalletSelector.tsx
> +
never ask for signing a login, all users not gonna use DMs, move it on messages page load!

2023-12-17 06:43 UTC, bigint commented on apps/web/src/components/Shared/Navbar/index.tsx
> +        <NavItem current={pathname === '/chat'} name="Chat" url="/chat" />
Remove this for now, i will add somewhere later near notification icon

2023-12-17 06:43 UTC, bigint commented on apps/web/src/hooks/useInitializedClient.tsx
> +    if (!data || status !== 'success') {
```suggestion
    }

    if (isLoading) {
      return;
    }

    if (!data || status !== 'success') {
```

2023-12-17 06:43 UTC, bigint commented on apps/web/src/pages/chat/index.tsx
> +// import { ContentTypeReaction } from '@xmtp/content-type-reaction';
Remove comments if not used, but its fine for now, can remove at last!

2023-12-17 06:43 UTC, bigint commented on packages/data/storage.ts
> +  TransactionStore: 'transaction.store',
trailing comma will fail with prettier

2023-12-18 08:10 UTC, closed without merging