feat: dockerize hey infra
heyxyz/hey pull request #4348
Opened 2023-12-26 07:10 UTC by ezhil56x

## What does this PR do?
- This PR is to implement dockerization to heyxyz/hey

## Related issues

Fixes #3898 
/claim #3898  

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Explanation of the changes
- Implemented dockerization to heyxyz
- Added documentation on `docs/devop.md`
- Can build docker images of `api`, `web`, and `og`
- Can deploy all these using `docker-compose.yml`
- `pnpm docker:build-api` to build docker image of `api`
- `pnpm docker:build-web` to build docker image of `web`
- `pnpm docker:build-og` to build docker image of `og`
- `pnpm docker:network` to create a `hey_network`
- `pnpm docker:deploy` to deploy all the images using `docker-compose/yml`

2023-12-26 16:08 UTC, bigint commented
@ezhil56x can you make a short video running this on docker 🙇🏼 ?

2023-12-26 17:02 UTC, ezhil56x commented
@bigint, Here is the working demo. Most time was for building images. Skip to last few minutes to see deployment

https://github.com/heyxyz/hey/assets/103899034/071bb25f-34f4-42ef-87c7-115e4c0dd40c

2023-12-26 17:06 UTC, bigint commented
manual env copy are hard with headless machines like railway 🙈

2023-12-26 17:08 UTC, ezhil56x commented
> manual env copy are hard with headless machines like railway 🙈

Only when we pass env as file in compose, it's working. Can I add a script than?

2023-12-26 17:18 UTC, bigint commented
for compose its fine, but while deploying docker to prod? is it possible to pass env vars?

2023-12-26 17:20 UTC, ezhil56x commented
> for compose its fine, but while deploying docker to prod? is it possible to pass env vars?

Yeah it is possible to pass through `docker run -e VARIABLE ...`

2023-12-28 10:12 UTC, ezhil56x commented
@bigint Any update? 🙈

2023-12-28 11:22 UTC, bigint commented
Can you deploy OG app to dockerhub and deploy in railway?

- We are missing devcontainers
- We are missing deployment workflows

2023-12-28 11:29 UTC, ezhil56x commented
> Can you deploy OG app to dockerhub and deploy in railway?
> 
> * We are missing devcontainers
> * We are missing deployment workflows

As discussed before having re

> Can you deploy OG app to dockerhub and deploy in railway?
> 
> * We are missing devcontainers
> * We are missing deployment workflows

As discussed before, hot reload uses only the node runtime instead of the run time that's on the host

Do you want me to deploy only the og app that is under `apps/og` for now?

2023-12-28 11:37 UTC, bigint commented
Yes you can deploy, so if we using only for deployment why we need compose file?

2023-12-28 11:39 UTC, ezhil56x commented
> Yes you can deploy, so if we using only for deployment why we need compose file?

Compose file is easy to use than `docker run ... ` and passing the env in cli

2023-12-28 11:42 UTC, bigint commented
Who will be the users gonna use docker compose? devs / devops?

2023-12-28 11:43 UTC, ezhil56x commented
> Who will be the users gonna use docker compose? devs / devops?

Devops

2023-12-28 12:12 UTC, bigint commented
Do they gonna use docker compose? im not sure it will be helpful if we are using railway 🙇🏼 cuz each service will be deployed on different servers

2023-12-28 12:13 UTC, ezhil56x commented
> Do they gonna use docker compose? im not sure it will be helpful if we are using railway 🙇🏼 cuz each service will be deployed on different servers

That can be removed if not needed. I have developed on Railway. Can you check you Dm on WA

2023-12-28 14:06 UTC, bigint requested changes

2023-12-28 14:06 UTC, bigint commented on .github/workflows/dockerhub.yml
> +      - name: Build and push web image
```suggestion
      - name: Build and push Web image
```

2023-12-28 14:06 UTC, bigint commented on .github/workflows/dockerhub.yml
> +      - name: Build and push api image
```suggestion
      - name: Build and push API image
```

2023-12-28 14:06 UTC, bigint commented on .github/workflows/dockerhub.yml
> +      - name: Build and push og image
```suggestion
      - name: Build and push OG image
```

2023-12-28 14:06 UTC, bigint commented on .github/workflows/dockerhub.yml
> +      - main
```suggestion
on:
  push:
    branches: [main]
```

2023-12-28 15:02 UTC, bigint approved these changes
**LGTM** :shipit: 

![LGTM](https://media3.giphy.com/media/dASc6rD8EOXEQ/giphy.gif)

2023-12-28 15:02 UTC, merged